config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :document_types
    resources :products do
      resources :documents do
        collection do
          post :update_positions
        end
      end
    end
  end
end

app/models/spree.rb
module Spree
  def self.table_name_prefix
    'spree_'
  end
end

app/models/spree/document.rb
class Spree::Document < ActiveRecord::Base
  belongs_to :product
  belongs_to :document_type

  validates :name, presence: true
  validates :product, presence: true
  #validates :document_type, presence: true

  has_attached_file :attachment
  validates_attachment :attachment, presence: true, content_type: { content_type: "application/pdf" }

  acts_as_list

  def document_type_name
    document_type.present? ? document_type.name : ''
  end
end

app/models/spree/document_type.rb
module Spree
  class DocumentType < ActiveRecord::Base
    has_many :documents, dependent: :restrict_with_error
    before_destroy :check_for_documents

    validates :name, presence: true, uniqueness: { case_sensitive: false }
    validates :internal_name, presence: true
  end
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :documents, -> { order(position: :asc) }
end

app/controllers/spree/admin/document_types_controller.rb
module Spree
  module Admin
    class DocumentTypesController < ResourceController
    end
  end
end

app/controllers/spree/admin/documents_controller.rb
module Spree
  module Admin
    class DocumentsController < ResourceController
      before_filter :load_product
      before_filter :load_document_types

      private
        def location_after_destroy
          admin_product_documents_url(@product)
        end

        def location_after_save
          admin_product_documents_url(@product)
        end

        def load_product
          @product = Product.friendly.find(params[:product_id])
        end

        def load_document_types
          @document_types = Spree::DocumentType.all
        end
    end
  end
end

app/views/spree/admin/document_types/_form.html.erb
<div data-hook="admin_document_form_fields" class="row">
  <div class="col-md-6">

    <div data-hook="name" class="form-group">
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div data-hook="internal_name" class="form-group">
      <%= f.label :internal_name, Spree.t(:internal_name) %>
      <%= f.text_field :internal_name, class: 'form-control' %>
      <p class="hint">Only change an existing internal name if you've checked with your developer!</p>
    </div>

  </div>
</div>

app/views/spree/admin/document_types/edit.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @document_type } %>

<% content_for :page_title do %>
  <%= t(:edit_document_type) %>
<% end %>

<%= form_for [:admin, @document_type] do |f| %>
  <fieldset data-hook="new_document_type">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_document_types_url, icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/document_types/index.html.erb
<% content_for :page_title do %>
  <%= t(:document_types) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to(t(:new_document_type), new_admin_document_type_url(), { class: "btn-success", icon: 'add', id: 'new_document_type_link' }) %>
<% end %>

<% if @document_types.any? %>
  <table class="table">
    <thead>
      <th>Name</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @document_types.each do |document_type| %>
        <tr id="<%= spree_dom_id(document_type) %>">
          <td><%= document_type.name %></td>
          <td class="actions">
            <%= link_to_with_icon('edit', t("edit"), edit_admin_document_type_url(document_type), :class => 'edit') %>
          </td>
          <td>
            <%= link_to_delete document_type, {:url => admin_document_type_url(document_type) }%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No document types.
<% end %>

app/views/spree/admin/document_types/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @document_type } %>

<% content_for :page_title do %>
  <%= t(:new_document_type) %>
<% end %>

<%= form_for [:admin, @document_type] do |f| %>
  <fieldset data-hook="new_document_type">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.create'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_document_types_url, icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/documents/_form.html.erb
<div data-hook="admin_document_form_fields" class="row">
  <div class="col-md-6">

    <%= f.hidden_field :product_id, { value: @product.id } %>

    <div data-hook="document_type" class="form-group">
      <%= f.label :document_type_id, Spree.t(:document_type) %>
      <%= f.select :document_type_id, options_for_select(@document_types.map { |dt| [dt.name, dt.id] }, @document.document_type), include_blank: true, class: 'form-control' %>
    </div>

    <div data-hook="name" class="form-group">
      <%= f.label :name, Spree.t(:name) %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div data-hook="file" class="form-group">
      <%= f.label :attachment, Spree.t(:filename) %>
      <%= f.file_field :attachment %>
      <% if f.object.attachment.file? %>
        <br />
        <%= link_to 'View Current Document', f.object.attachment.url, target: :_blank, class: 'btn btn-default' %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/documents/edit.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<% content_for :page_title do %>
  <%= t(:new_document) %>
<% end %>

<%= form_for [:admin, @product, @document], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_document">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_documents_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/documents/index.html.erb
<%= render :partial => 'spree/admin/shared/product_tabs', :locals => {:current => "Documents"} %>

<% content_for :page_actions do %>
  <%= button_link_to(t(:new_document), new_admin_product_document_url(@product), { class: "btn-success", icon: 'add', id: 'new_idocument_link' }) %>
<% end %>

<table class="table sortable" data-sortable-link="<%= update_positions_admin_product_documents_url(@product) %>">
  <thead>
    <th>Sort</th>
    <th>Type</th>
    <th>Name</th>
    <th>Document</th>
    <th></th>
    <th></th>
  <thead>

  <% @product.documents.each do |document| %>
    <tr id="<%= spree_dom_id(document) %>">
      <td class="move-handle"><span class="icon icon-move handle"></span></td>
      <td><%= document.document_type_name %></td>
      <td><%= document.name %></td>
      <td><%= link_to document.attachment_file_name, document.attachment.url, target: :_blank %>
      <td class="actions">
        <%= link_to_with_icon('edit', t("edit"), edit_admin_product_document_url(@product, document), :class => 'edit') %>
      </td>
      <td>
        <%= link_to_delete document, {:url => admin_product_document_url(@product, document) }%>
      </td>
    </tr>
  <% end %>
</table>

app/views/spree/admin/documents/new.html.erb
<%= render partial: 'spree/admin/shared/error_messages', locals: { target: @product } %>

<% content_for :page_title do %>
  <%= t(:new_document) %>
<% end %>

<%= form_for [:admin, @product, @document], html: { multipart: true } do |f| %>
  <fieldset data-hook="new_document">
    <%= render partial: 'form', locals: { f: f } %>

    <div class="form-actions" data-hook="buttons">
      <%= button Spree.t('actions.update'), 'save' %>
      <span class="or"><%= Spree.t(:or) %></span>
      <%= button_link_to Spree.t('actions.cancel'), spree.admin_product_documents_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/shared/_documents_tabs.html.erb
<li class='icon-link <%= "active" if current == 'Documents' %>'>
  <%= link_to_with_icon 'file', t("documents"),  admin_product_documents_url(@product)  %>
</li>